name: build-shaderc

on:
  push:
    branches:
      - master
jobs:
  
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build Script
        id: build
        shell: cmd
        run: call build.cmd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shaderc-v2024.4
          path: shaderc-v2024.4.zip
          if-no-files-found: error
          compression-level: 0

  release:
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
      SHADERC_VERSION: v2024.4
    steps:

      - name: Create GitHub Release
        run: |
          echo v2024.4>>notes.txt
          gh release create v2024.4 -R "${GITHUB_REPOSITORY}" -t 'v2024.4' -F notes.txt

      - name: Get Artifacts From Build Steps
        uses: actions/download-artifact@v4
        with:
          pattern: shaderc-*.zip
          merge-multiple: true

      - name: Upload Artifacts to GitHub Release
        run: gh release upload 'v2024.4' shaderc-*.zip -R "${GITHUB_REPOSITORY}"
